# Основные настройки
field_separator: ","
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: target

# Поля данных
USER_FEATURE_FIELD: user_age,Gender
ITEM_FEATURE_FIELD: video_source_id,video_duration

# Формат данных
load_col:
    inter: [user_id, item_id, target]
    user: [user_id, user_age, Gender]
    item: [item_id, video_source_id, video_duration]

# Модель и гиперпараметры
model: DeepFM
embedding_size: 64
learning_rate: 0.001
epochs: 50
train_batch_size: 256
eval_batch_size: 256
device: cuda:0